### ISSUE TITLE
Internal anchors are broken

### ISSUE THREAD

**Issue by muflone** [iusvar/grav-plugin-printfriendly#2]
Hi

enabling the printfriendly plugin all the internal anchors (page#anchor_name) are broken, making them duplicated inside the hidden div dialogDiv.

A simple workaround would be to move the dialogDiv after the real content, in this way the anchor will automatically point the first found, then the anchor not hidden.

Tested under:
OS: Arch Linux x86_64
Browsers: Firefox 48.0.2 and Google Chrome 53.0

**Comment by laurent-steamlead** [comment]
just to bring some elements, the duplicate content created by print friendly can also cause troubles with other plugins. For exemple it can't work as it is with the anchors and tablesorter plugins.

Putting the added content at the end of the body can be an improvement. 
Identifying the added content (for instance, by adding a start and an end HTML comment) can also be useful.

So, it could eventually be filtered by other plugins

I'll try to do that in a fork

**Comment by iusvar** [comment]
Hi,
I also use the plugins anchors: I have a look but i can not find ids and double url fragments. For example [http://iusvar.hostfree.pw/ef5/#print-friendly-plugin-3](http://iusvar.hostfree.pw/ef5/#print-friendly-plugin-3) than [http://iusvar.hostfree.pw/ef5/#print-friendly-plugin-1](http://iusvar.hostfree.pw/ef5/#print-friendly-plugin-1) inside the hidden div .. .

As far as the plugin tablesorter I will do some checks ...

**Comment by laurent-steamlead** [comment]
concerning the anchors plugins, I've extended it by adding a TOC in the sidebar (by following the exemple given in [its doc](https://jsfiddle.net/bryanbraun/x85hfvbk/).

As it, I can have an automatic TOC , but I had to find a way to exclude the content generated by the PP plugin, because if not, all my headers links were duplicated.
You can find a practical exemple in my [blog](http://www.gamecoderblog.com/fr/courses-review)

I've also found a solution for the tablesorter plugin: I had to submit some change to its author to allow a global table usage (instead of a per table settings only), and I've extended the PP settings by adding a tab for stripping some texts in the page content. As it I can remove some of the CSS classes added by the tablesorter in the content of the PP preview.

You can check my forks of these plugins to get an idea of what I've done

- [tablesorter](https://github.com/steamlead/F_grav-plugin-tablesorter)
- [anchors](https://github.com/steamlead/F_grav-plugin-anchors)
- [printfriendly](https://github.com/steamlead/F_grav-plugin-printfriendly)

**Comment by iusvar** [comment]
Thanks for the tips...

In my opinion, as far as possible, each plugin should not interfere with other plugins.

Now, having entered what is to be printed in a hidden input field, there are no interferences with the Anchors, Tablesorter and Toc plugins.

I just created a new version of the procedure.

Greeting
