### ISSUE TITLE
Error "Page not Found"

### ISSUE THREAD

**Issue by LaurentOngaro** [iusvar/grav-plugin-printfriendly#4]
Hi,
It seems that the page is not found when I click on the print button on the pages of my blog. It's probably an issue with the route (slug ?) of the pages.

You can see the error on any page of my blog , for instance : 
http://www.gamecoderblog.com/fr/unreal-engine4/ue4-recommended-folder-structure

Tested with the lastest version of Grav, a personnal theme (GCB that is just an antimatter theme override), and prettyprint v0.3.1
Lost of plugins enabled (not sure it has any influence on the issue)
Multilanguage enabled (english and french, possible influence on the issue))

**Comment by iusvar** [comment]
Hi, 
using Chrome > Developer Tools > Application > Frames > Scripts (and Stylesheets), I do not see **jQuery UI** libraries and their css sheets ...

**Comment by LaurentOngaro** [comment]
normally I haven't made specific changes for the 3.0.1 version in my blog. 

After checkink its conf:
for jquery : 
- source was maxCDN
- version was 1.12.0 (by default), probably because I've installed previous versions of your plugin before

I've changed to 1.12.1 , same error occurs

**Comment by iusvar** [comment]
I've made some changes that improve the slug selection. Within a short time the new version should be available on GPM

**Comment by LaurentOngaro** [comment]
hi, I've updated my blog with the last version of your plugin and the issue is still present.
I'll try to test with a clen Grav install

**Comment by LaurentOngaro** [comment]
Hi, 
I can't find where the problem is with this version of the plugin.

I've created an dev version for you, that just uses the lastest Grav version, a few plugins and the lastest version of PF.
It will be available at http://dev.gamecoderblog.com in a few minutes
Just clic on the blog Menu (top right of the home page), and clic on the print button of the post. 
Now the error is an http 500.
If you need to access to the admin, just send me a PM. 
I could also send you the source files.

I'll get back to the 0.2.x version on my blog, that was working well, and I'll test your next releases on my dev blog.

Good luck and Best regards
laurent

**Comment by LaurentOngaro** [comment]
hi, 
JFYI , the 0.3.3 version doesn't produce an error, but the content of the printed page is empty
you can see it on the test blog at http://dev.gamecoderblog.com in a few minutes.

**Comment by LaurentOngaro** [comment]
Hi, I think I've found the cause of the issue.
It's due to the param_sep value in the system.yaml file
if it's set to ";" (to make Grav fully compatible with a windows system, as mine)  the issue "page not found" or sometimes "http 500" occurs.
If it's set on ":" as default, there is no issue

**Comment by LaurentOngaro** [comment]
I've found the solution! 
Mainly you should pass the parameters to your ajax call using a post method instead of get.
I'll submit a pull request, as it you can add the fix to your code if you want

**Comment by iusvar** [comment]
**Thank you for your desire to look for a solution.** That is not the right one though.

On my local computer:
* Apache / 2.4.7 (Ubuntu)
* PHP Version 5.5.9-1ubuntu4.21

I get the same error that you get on the online server (Not found).

* You say that the cause of the error was due to param_sep parameter value in system.yaml: unfortunately I did not use it because I entered ":" in code directly.
* Then say that if the value of param_sep is set to ":" as default, there is no issue: that's what I said before.

So, I looked for some similarity in the code of some Grav Team plugins: in particular I looked at the [Login plugin](https://github.com/getgrav/grav-plugin-login/blob/develop/classes/Login.php#L261-L262).

I will adapt to the coding adopted by the Team Grav: **I will use the parameter param_sep.**

Meanwhile, you could try that part of code that I reported above (of the Login plugin): the code handles sending mail when a new account is activated.
